name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT_ID: 412631849822
  AWS_REGION: eu-north-1
  AWS_ECR_REPO: sofia/mvnproject2
  AWS_ECR_URL: 412631849822.dkr.ecr.{AWS_REGION}.amazonaws.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Construir aplicación
        run: mvn clean package

      - name: Iniciar sesión en AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${AWS_ECR_URL}

      - name: Construir y subir Docker a ECR
        run: |
          docker build -t mi-aplicacion2 .
          docker tag mi-aplicacion2 ${AWS_ECR_URL}/${AWS_ECR_REPO}
          docker push ${AWS_ECR_URL}/${AWS_ECR_REPO}
